name: cicd
on:
  push:
    branches:
      - feature/build-pipeline
      - main
  pull_request:
    branches:
      - main

jobs:
  #compile:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: debug
        run: ls -la ./target | grep .jar

      - run: mkdir files
      - uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            target/*.jar
            Dockerfile
            src/main/k8s/deployment.yaml


  build_image:
    needs: [build_jar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files
          path: |
            target/*.jar
            Dockerfile
            src/main/k8s/deployment.yaml
            
      - name: Display structrue of download files
        run: ls -R



  push_to_dockerhub:
    needs: [build_image]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v3
#        with:
#          images: my-docker-hub-namespace/my-docker-hub-repository

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}




  #deploy_to_kubernetes: