name: cicd
on:
  push:
    branches:
      - feature/build-pipeline
      - main
  pull_request:
    branches:
      - main

jobs:
  #compile:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: debug
        run: ls -la ./target | grep .jar

      - run: mkdir staging && cp target/*.jar staging && cp Dockerfile staging && cp src/main/k8s/deployment.yaml staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging


  build_image:    #hier dann download-> jar && dockerfile && deployment.yaml
    needs: [build_jar]
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: Package
          path: staging

      - name: Display structrue of download files
        run: ls -R



      #push_to_dockerhub:
  #deploy_to_kubernetes: