name: cicd
on:
  push:
    branches:
      - feature/build-pipeline
      - main
  pull_request:
    branches:
      - main

jobs:
  #compile:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: debug
        run: ls -la ./target | grep .jar

      - run: mkdir files
      - uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            target/*.jar
            Dockerfile
            src/main/k8s/deployment.yaml


  build_and_push_to_dockerhub:
    name: Push Docker image to Docker Hub
    needs: [build_jar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files
          path: |
            target/*.jar
            Dockerfile
            src/main/k8s/deployment.yaml

      - name: Display structrue of download files
        run: ls -R

 #     - name: Set up QEMU
 #       uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
 #         context: .
          push: true
          tags: workshop-sensor-data-collector:latest





  #deploy_to_kubernetes: